### ISSUE TITLE
"classes.pkl" and "ContactSigSMPL.pkl" is missing

### ISSUE THREAD

**Issue by vra** [muelea/tuch#1]
Hi @muelea , Thanks for sharing your program with us, it' clean and helpful.
When running the `SMPLify-DC demo` command, I found that the pkl files are missing:
```bash
python demo_smplify_dc.py --name smplify_dc --log_dir out/demo_smplify_dc --ds_names dsc_df \
--num_smplify_iters 100
Traceback (most recent call last):
  File "demo_smplify_dc.py", line 183, in <module>
    main(options)
  File "demo_smplify_dc.py", line 45, in main
    dataset = BaseDataset(options, options.ds_names[0], use_augmentation=False)
  File "/data_1/xxx/projects/github/tuch/tuch/datasets/base_dataset.py", line 67, in __init__
    self.classes = pickle.load(open(osp.join(config.DSC_ROOT, 'classes.pkl'), 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: '/data_1/xxx/datasets/DSC/classes.pkl'
```
Could you please upload "classes.pkl" and "ContactSigSMPL.pkl" ? Thanks

**Comment by muelea** [comment]
Hi vra,

thanks a lot for your feedback. I am sorry about the missing files. Here you go:
[classes.pkl](https://owncloud.tuebingen.mpg.de/index.php/s/46mGdKsb2HLEZzR) [ContactSigSMPL.pkl](https://owncloud.tuebingen.mpg.de/index.php/s/Y6Lz99w6SH7aaSM)

Best wishes,
Lea

**Comment by vra** [comment]
Hi Lea,
Thanks for your quick reply, very cool!
