### ISSUE TITLE
how to render the smpl ground truth of mtp dataset?

### ISSUE THREAD

**Issue by YongtaoGE** [muelea/tuch#2]
Hi, @muelea ! Thanks for your great work. I found the mtp dataset only provides smpl pose and shape parameter, missing the smpl transition parameter and camera parameters. I want to render the smpl ground truth on the image. It would be very much appreciated if you have any advice on this.

**Comment by muelea** [comment]
Hi YongtaoGe,

the original MTP data (smpl-x) has camera parameters, which you can use to project the meshes. The TUCH map data are just the original parameters transferred to smpl. During TUCH training, the camera rotation is zero (unit) and the camera translation is estimated:
https://github.com/muelea/tuch/blob/818936c630ee505515d1a221c13d689014fbcf55/tuch/train/train_module.py#L171

**Comment by YongtaoGE** [comment]
Thanks for you help
